import { db } from "@/utils/db";
import { sessionChart } from "@/utils/schema";
import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { sessionId, sessionDetail, messages } = body;

    if (!sessionId || !sessionDetail || !messages) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const { selectedDoctor, notes } = sessionDetail;

    const prompt = `
      You are an expert medical scribe. Analyze the following conversation between a user and an AI Medical Agent (${selectedDoctor.specialist}).
      User's initial chief complaint notes: "${notes}"

      Conversation Transcripts:
      ${JSON.stringify(messages, null, 2)}

      Generate a structured medical report based on this conversation.
      You MUST return ONLY a valid JSON object with the following structure, with NO Markdown wrappers like \`\`\`json:
      {
        "agentName": "${selectedDoctor.specialist}",
        "chiefComplaint": "string (summarize the main issue)",
        "summary": "string (1-2 paragraph summary of the consultation)",
        "symptoms": [{"symptom": "name of symptom", "duration": "string", "severity": "string"}],
        "medicationMentioned": [{"name": "string", "dosage": "string", "frequency": "string"}],
        "recommendations": ["string (actionable next steps)"],
        "disclaimer": "This report was generated by AI. Please consult a real doctor for medical advice."
      }
    `;

    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash", generationConfig: { responseMimeType: "application/json" } });
    const result = await model.generateContent(prompt);
    let reportJsonText = result.response.text();

    const reportObj = JSON.parse(reportJsonText);

    // Update DB
    await db
      .update(sessionChart)
      .set({
        conversation: messages,
        report: reportObj,
      })
      .where(eq(sessionChart.sessionId, sessionId));

    return NextResponse.json({ success: true, report: reportObj });
  } catch (error) {
    console.error("Error POST /api/medical-report:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
